name: Compile and Test
on: [push]
jobs:
  compile-and-test:
    strategy:
      matrix:
        include:
          - container: gcc:10
            cc: gcc
          - container: gcc:11
            cc: gcc
          - container: silkeh/clang:11
            cc: clang
          - container: silkeh/clang:12
            cc: clang
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.cc }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites"
        run:  apt update && apt install -y libcunit1-dev
      - name: Run tests
        run: make -C tests/automated clean test
      - name: Build library
        run: make bin/nanocbor.so
      - name: Build example
        run: make -C examples/pretty-printer pretty-printer

